### PR TITLE
Issue #67 Add Additional Sharing Options

### LINKED ISSUE #67: Add Additional Sharing Options
https://github.com/user-attachments/assets/27f86f23-47cb-4f23-99a9-9824e609b934
Add Sharing options like WhatsApp, Instagram, Twitter etc...

### PR DESCRIPTION
**Pull request by vverma022**
### Added Additional Sharing Options
##Description:
This pull request introduces additional sharing options for the application. Users can now share content directly to WhatsApp, Twitter, and Instagram. The implementation includes:

WhatsApp: Redirects to WhatsApp with the content link.

1. Twitter: Opens a tweet compose window with the content link.

1. Instagram: Copies the link to the clipboard for manual sharing (as direct URL sharing is not supported).

##Changes:

1. Updated handleShare function to handle new sharing options.

1. Added buttons for WhatsApp, Twitter, and Instagram in the sharing dialog.

##Testing:

1. Verified that sharing to WhatsApp and Twitter works as expected.

2. Confirmed that the Instagram sharing option correctly copies the link to the clipboard.

Closes #67 
Screenshot 2024-09-12 at 7 56 04 PM

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Can we have a dropdown for this? Dialog seems a bit disctracting. Dropdown will have a better UX

**Comment by vverma022** [comment]
Alright I convert it to a drop-down.

**Comment by vverma022** [comment]
> Can we have a dropdown for this? Dialog seems a bit disctracting. Dropdown will have a better UX

Screenshot 2024-09-14 at 1 34 36 AM

**Comment by SujithThirumalaisamy** [comment]
Thankyou sir. Great work

**Pull request merged**
