### PR TITLE
chore: add preinstall script to enforce pnpm usage as the package manager

### PR DESCRIPTION
**Pull request by geekyharsh05**
## This pr fixes the issue #34:
- ### Only allow pnpm as the package manager in the project

### Yarn:
Screenshot 2024-08-30 at 8 19 07 PM <br />

### NPM:
Screenshot 2024-08-30 at 8 19 31 PM

### CODE REVIEW

**Comment by geekyharsh05** [comment]
@hkirat is it ok?

**Comment by geekyharsh05** [comment]
@SujithThirumalaisamy Can you please review it?

**Comment by SujithThirumalaisamy** [comment]
please add the pnpm-lock back to the commit and also resolve the conflicts. also remove .DS file

**Comment by geekyharsh05** [comment]
@SujithThirumalaisamy Ok sir!

**Comment by SujithThirumalaisamy** [comment]
Please open a new PR only with the preinstall scripts Merged the docker changes in #30

**Comment by geekyharsh05** [comment]
@SujithThirumalaisamy ok

**Pull request closed without merging**
