### PR TITLE
toast configuration has been added

### PR DESCRIPTION
**Pull request by RajuShivarama**

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
https://github.com/code100x/muzer/blob/76be1650935af46e4d92fee69ef892b4bd98a3e0/app/components/StreamView.tsx#L265

You should Ideall move this file to the root layout. and configure this. It seems that it have the configuration. But its not in the root. Remove the configs in the `toast()` calls

**Comment by RajuShivarama** [comment]
Made changes, please check it once

**Comment by SujithThirumalaisamy** [comment]
LGTM!

**Comment by SujithThirumalaisamy** [comment]
Can you please fix the conflicts. And also recent commits had added some more toast with these configs. Can you please remove that. Happy to merge it ASAP

**Comment by SujithThirumalaisamy** [comment]
Please resolve the conflicts

**Pull request closed without merging**
