### PR TITLE
feat: setup next-themes and configured it throughout

### PR DESCRIPTION
**Pull request by ItsFlash10**
Fixes: #92 
@SujithThirumalaisamy 
1. Added next-themes.
2. Setup `prettier-plugin-tailwindcss`

https://github.com/user-attachments/assets/e4acecb1-3d2d-4467-9f86-409fcb79057b

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Can you add a similar video ref on the dashboard?

**Comment by SujithThirumalaisamy** [comment]
Looks good happy to merge after #95 That have a bunch of things. May create a conflict. Happy to merge it soon. Great work sir. Please add some video on dashboard

**Comment by ItsFlash10** [comment]
@SujithThirumalaisamy Done

https://github.com/user-attachments/assets/8f53085d-81c6-4579-a1d8-1a601528b98f

**Comment by SujithThirumalaisamy** [comment]
Great work buddy

**Pull request merged**
