### PR TITLE
Create landing page

### PR DESCRIPTION
**Pull request by Pawank06**
## Overview
This PR addresses the issue #100  to improve user experience and modernize the overall look and feel.

## Changes Made:

Created the landing page for the muzer.

1. **Landing Page:**

- Created a more **welcoming and clean** first impression.
- Added some animation.

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Add a video reference

**Comment by Pawank06** [comment]
> Add a video reference


https://github.com/user-attachments/assets/ac4c181c-48d8-4f91-bf10-8bf7799dfb0d

**Comment by SujithThirumalaisamy** [comment]
image
Can you please also add the existing key features section in this.

**Comment by Pawank06** [comment]
> image Can you please also add the existing key features section in this.

I'm finding some good feature references to align with the design. I'll take care of it.

**Comment by SujithThirumalaisamy** [comment]
If you are planning to do all the FE changes which mentioned in #100 Can you please merge it to the `revamp/ui` branch?
Raise the PR there. Will merge that there and people can follow that up

**Pull request closed without merging**
