### PR TITLE
chore: added singleton db, added .env.example, added pre commit hook, eslint and prettier

### LINKED ISSUE #4: Add a Singleton db and add .env.example
Self explanatory

### PR DESCRIPTION
**Pull request by Sahid-m**
Added singleton db and added .env.example also changed spaces due to lint issue 

Fixes #4

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
There is a lot of linting noice. Can you fix that?

**Comment by Sahid-m** [comment]
Sure ser

**Comment by Sahid-m** [comment]
Do I add configure es lint for the project as it would be more helpful for future contributions as well?

**Comment by Sahid-m** [comment]
Sure will do that

**Comment by Sahid-m** [comment]
> > Do I configure es lint for the project as it would be more helpful for future contributions as well?
> 
> Yeah will be good I guess. If you also write a workflow for that to check the lint. That will also be great

I've added scripts for linting and formatting but the pr would be too big if i format the code now, also added pre commit hook with husky that way we don't need Github actions so is it okay ?

**Comment by SujithThirumalaisamy** [comment]
Husky works

**Comment by Sahid-m** [comment]
@SujithThirumalaisamy ser sorry ping but please review!

**Comment by thepradipvc** [comment]
Hey @SujithThirumalaisamy,
Can you look into this one as it will help a lot in the review also, the diffs people are pushing currently are too messy.
LGTM.

**Comment by SujithThirumalaisamy** [comment]
Can you please resolve the conflicts. Also only keep the precommit and eslint changes. Everything else is merged with other PRs. Happy to merge this soon

**Comment by Sahid-m** [comment]
Alright will do that.

**Comment by SujithThirumalaisamy** [comment]
Closing it for now. Waiting for a new PR. Thankyou!

**Comment by Sahid-m** [comment]
shouldn't we make repo a turbo repo first as there are two apps ? it would be repetitive to add es lint, and other pre commit hooks to both?

**Comment by SujithThirumalaisamy** [comment]
Do we dont need turbo repo. Just add it for both the folders

**Pull request closed without merging**
