### PR TITLE
Signup/Login with credentials, Generated username, Edit username, upload particular song once

### LINKED ISSUE #40: Add a username
Creator should be able to select a username after signup
Their page should be available on https://muzer.100xdevs.com/creator/kirat

### LINKED ISSUE #52: User can upload same song multiple times
### Current Behavior:

A user can upload a song as many times as he wants. And if some other user adds the same song, it again adds to the queue.

### Expected Behavior:

A user can only upload a particular song only once. And if another user uploads the same song, that song gets upvoted.

### PR DESCRIPTION
**Pull request by harmanbatheja15**
Fixes #40  
Fixed #52 

- Added signup/login with credentials and generated username based on user's Email ID.
- Hashed Password stored in DB.
- Added Update Username feature.
- User can't edit email (Email field is disabled).
- A user can upload a particular song only once. And if another user uploads the same song, that song gets upvoted.

Screenshot 2024-08-31 at 4 08 20 AM

Screenshot 2024-08-31 at 4 08 42 AM

Screenshot 2024-08-31 at 4 27 14 AM

### CODE REVIEW

**Comment by harmanbatheja15** [comment]
@hkirat

**Comment by harmanbatheja15** [comment]
@hkirat Added more things:
- Hashed Password
- Added **Update Username** feature

Screenshot 2024-08-31 at 5 49 50 AM

**Comment by harmanbatheja15** [comment]
- Added signup/login with credentials and generated username based on user's Email ID.
- Hashed Password
- Added Update Username feature
- user can't edit email field (Email field is disabled)
- A user can upload a particular song only once. And if another user uploads the same song, that song gets upvoted.

@hkirat @Bot-Rakshit Please check this out!

**Comment by SujithThirumalaisamy** [comment]
Not necessary. Also a lot of conflicts

**Comment by SujithThirumalaisamy** [comment]
Also create a separate PR for the username selection

**Comment by harmanbatheja15** [comment]
> Also create a separate PR for the username selection

okay

**Pull request closed without merging**
