### PR TITLE
Integrate web3 payments

### PR DESCRIPTION
**Pull request by VK-RED**
Resolves: #72 

## Features

- Added Solana Support
- User can pay and play the song immediately.

### Screencasts

[Screencast from 2024-09-05 22-26-08.webm](https://github.com/user-attachments/assets/252a2e63-5055-446b-808b-027fb164ec3d)

### CODE REVIEW

**Comment by VK-RED** [comment]
@hkirat any review on this bhaiyaa !!

**Comment by SujithThirumalaisamy** [comment]
Can you please follow up with these
1. `/dashboard` is an admin kind of route. Which should not have the payment stuffs
2. Add a constant for the amount of SOL per play.

**Comment by VK-RED** [comment]
hi @SujithThirumalaisamy 

1) Will make sure that it is only possible at the creator/[creatorId] page

2) The constants was also added already https://github.com/code100x/muzer/pull/73/files#diff-8ae7728e72c89a6863e99fb6f127a607dff62f235ac848d6366eceef5176eaaeR1

Will resolve the conflicts

**Comment by SujithThirumalaisamy** [comment]
Merged a PR for this. Thankyou for your effort. Creating some issues. Feel free to work on that

**Pull request closed without merging**
