### PR TITLE
feat: Add Metadata

### PR DESCRIPTION
**Pull request by Mihir2423**
### Overview
This PR adds metadata to the website for better SEO.

### Changes Made
- Added OG Image
- Updated Meta Data (title, description and keywords)
- Added new favicon 

### Proof of Changes

Screenshot 2024-09-19 at 1 18 56 PM

Tested on : https://www.opengraph.xyz/
By hosting the app on my side.

### ENV Changes
NEXTAUTH_URL=https://muzer.100xdevs.com

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Why the image is present two times in two different folders?

**Comment by SujithThirumalaisamy** [comment]
Is the Icon free to use? Dont we get aany issues?

**Comment by Mihir2423** [comment]
> Why the image is present two times in two different folders?

Sometimes, Next.js/Vercel glitches, so it's better to keep the image in both the `app` folder and the `public` folder.

**Comment by Mihir2423** [comment]
> Is the Icon free to use? Dont we get aany issues?

It might require us to give them credit since I downloaded it from Flat Icons.

**Comment by Mihir2423** [comment]
@SujithThirumalaisamy , Please review this or it might create conflicts after major ui change revamp.

**Comment by SujithThirumalaisamy** [comment]
Can you please use this icon `https://cdn.isujith.dev/muzer_icon.ico`

**Comment by Mihir2423** [comment]
> Can you please use this icon `https://cdn.isujith.dev/muzer_icon.ico`

Updated!

**Pull request merged**
