### PR TITLE
Feature/invalid link

### PR DESCRIPTION
**Pull request by DevItaliya22**
solved issue #15

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
follow up: Please remove the lock files also

**Comment by DevItaliya22** [comment]
> follow up: Please remove the lock files also

Done

**Comment by SujithThirumalaisamy** [comment]
Can you please resolve the conflicts

**Comment by SujithThirumalaisamy** [comment]
Closing this for now. Please reopen this one with the respective changes

**Pull request closed without merging**
