### PR TITLE
Feature/web socket

### PR DESCRIPTION
**Pull request by atul24112001**
#27

### CODE REVIEW

**Comment by atul24112001** [comment]
This is web socket implementation.

Q: Why so many file changes ??
Ans: shifted nextJs app form . to ./next-app folder

Note: Main file/folders to focus on

ws/src/
next-app/app/dashboard/page.tsx
next-app/app/creator/[...creatorId]/page.tsx
next-app/app/components/StreamView.tsx

**Comment by atul24112001** [comment]
Hey @hkirat , I know this is not the best please have a look on four files that I have mentioned in previous comment.

**Comment by atul24112001** [comment]
https://github.com/user-attachments/assets/4ab65de7-0550-486a-8719-ceee879b889f

Local sample of current logic -> i am running 2 instance of the ws server.

**Comment by atul24112001** [comment]
https://muzer.atulmorchhlay.com/
@hkirat

**Comment by atul24112001** [comment]
Hey @hkirat, Updated web-socket logic according to new changes.

**Comment by SujithThirumalaisamy** [comment]
Looks good. But can you please resolve the conflicts

**Comment by atul24112001** [comment]
@SujithThirumalaisamy done

**Comment by SujithThirumalaisamy** [comment]
> Hey @SujithThirumalaisamy , I have updated build.yml according to my understanding please check that.

Thankyou so muck. Great work. Testing it in local

**Pull request merged**
