### PR TITLE
Improved mobile UI layout for LandingPage component

### PR DESCRIPTION
**Pull request by anudeep009**
Screenshot 2024-08-29 211241
Screenshot 2024-08-29 211254
Adjusted the mobile UI layout to enhance readability and visual hierarchy.
Increased spacing between elements and improved font sizes for better mobile responsiveness.

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Looks good. Please remove the lock file

**Comment by anudeep009** [comment]
> Looks good. Please remove the lock file

I’ve removed the lock file as requested.

**Comment by SujithThirumalaisamy** [comment]
Can you please also resolve the consflicts

**Comment by SujithThirumalaisamy** [comment]
Done at #62 Thankyou for the efforts sir

**Pull request closed without merging**
